#!/usr/bin/env python3
"""Job: create-pr — open PR, post inline comments, resolve fixed threads."""
import os, subprocess, sys, textwrap, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import *

owner, repo_name = REPO.split("/", 1)

# ── Load pipeline state ───────────────────────────────────────────────────────
r1_code     = read_pipeline("code-r1.json")     or []
r2_code     = read_pipeline("code-r2.json")            # None = round 2 didn't run
r1_findings = read_pipeline("findings-r1.json") or []
r2_findings = read_pipeline("findings-r2.json")        # None = round 2 didn't run

final_code     = r2_code or r1_code
final_findings = r2_findings if r2_findings is not None else r1_findings
rounds_done    = 2 if r2_code else 1

# A finding is resolved if it appeared in r1 but not in r2 (after round 2 ran)
def _key(f): return (f.get("file", ""), f.get("line", 0))
r1_keys = {_key(f) for f in r1_findings}
r2_keys = {_key(f) for f in (r2_findings or [])} if r2_findings is not None else set()

resolved_findings   = [f for f in r1_findings if r2_findings is not None and _key(f) not in r2_keys]
unresolved_findings = final_findings

# ── Build PR body ─────────────────────────────────────────────────────────────
files_list = "\n".join(f"- `{c['file']}`" for c in final_code)

if unresolved_findings:
    findings_md = "\n".join(
        f"- **[{f.get('severity','?')}]** `{f.get('file','')}:{f.get('line','')}` — {f.get('issue','')}"
        for f in unresolved_findings
    )
    review_section = f"\n### ⚠️ Unresolved — needs human review\n{findings_md}"
else:
    review_section = "\n### ✅ Reviewer approved — no findings."

pr_body = textwrap.dedent(f"""
    ## 🤖 AI-Generated Implementation

    Closes #{ISSUE_NUMBER}

    | Role | Model | Vendor |
    |---|---|---|
    | Coder | `{CODER_MODEL}` | OpenAI |
    | Reviewer | `{REVIEWER_MODEL}` | Mistral |

    **Rounds:** {rounds_done} &nbsp;|&nbsp; **Files changed:** {len(final_code)} &nbsp;|&nbsp; **Resolved:** {len(resolved_findings)} &nbsp;|&nbsp; **Unresolved:** {len(unresolved_findings)}

    ### Files changed
    {files_list}
    {review_section}

    ---
    *Auto-generated by the agentic pipeline via GitHub Models.*
""").strip()

# ── Create PR ─────────────────────────────────────────────────────────────────
result = subprocess.run(
    ["gh", "pr", "create",
     "--title", f"feat: #{ISSUE_NUMBER} — {ISSUE_TITLE[:70]}",
     "--body", pr_body,
     "--head", BRANCH,
     "--base", "main",
     "--draft"],
    capture_output=True, text=True,
    env={**os.environ, "GH_TOKEN": GH_PAT or GITHUB_TOKEN},
)
if result.returncode != 0:
    print(f"[ERROR] PR creation failed:\n{result.stderr}", file=sys.stderr)
    post_issue_comment(
        f"❌ Pipeline complete but PR creation failed.\n"
        f"Branch `{BRANCH}` is ready — open the PR manually."
    )
    sys.exit(1)

pr_url    = result.stdout.strip()
pr_number = int(pr_url.rstrip("/").split("/")[-1])
print(f"PR: {pr_url}")

# ── Get PR head commit SHA ────────────────────────────────────────────────────
pr_resp   = github_api("GET", f"/repos/{owner}/{repo_name}/pulls/{pr_number}")
commit_sha = pr_resp.json()["head"]["sha"]

# ── Post inline review comments ───────────────────────────────────────────────
all_comments = []
for f in resolved_findings:
    all_comments.append({
        "path": f.get("file", ""),
        "line": max(1, int(f.get("line", 1))),
        "body": (
            f"**✅ RESOLVED [{f.get('severity','?')}]**\n\n"
            f"**Issue:** {f.get('issue','')}\n\n"
            f"**Suggestion:** {f.get('suggestion','')}\n\n"
            f"> Fixed by AI coder in round 2."
        ),
        "_resolved": True,
    })
for f in unresolved_findings:
    all_comments.append({
        "path": f.get("file", ""),
        "line": max(1, int(f.get("line", 1))),
        "body": (
            f"**⚠️ UNRESOLVED [{f.get('severity','?')}]**\n\n"
            f"**Issue:** {f.get('issue','')}\n\n"
            f"**Suggestion:** {f.get('suggestion','')}\n\n"
            f"> Needs human review."
        ),
        "_resolved": False,
    })

posted_inline = []
failed_comments = []

for c in all_comments:
    review_payload = {
        "commit_id": commit_sha,
        "event": "COMMENT",
        "comments": [{"path": c["path"], "line": c["line"], "side": "RIGHT", "body": c["body"]}],
    }
    r = github_api("POST", f"/repos/{owner}/{repo_name}/pulls/{pr_number}/reviews",
                   json=review_payload)
    if r.ok:
        posted_inline.append(c)
        print(f"  inline comment: {c['path']}:{c['line']}")
    else:
        print(f"  [WARN] inline failed ({r.status_code}) for {c['path']}:{c['line']} — falling back to PR comment")
        failed_comments.append(c)

# Fallback: post failed ones as top-level PR comments
for c in failed_comments:
    label = "✅ RESOLVED" if c["_resolved"] else "⚠️ UNRESOLVED"
    fallback_body = f"{label} — `{c['path']}:{c['line']}`\n\n{c['body']}"
    github_api("POST", f"/repos/{owner}/{repo_name}/issues/{pr_number}/comments",
               json={"body": fallback_body})

# ── Resolve threads for fixed findings ───────────────────────────────────────
resolved_to_collapse = [c for c in posted_inline if c["_resolved"]]
if resolved_to_collapse:
    time.sleep(2)  # let GitHub index the new comments

    threads_query = """
    query($owner: String!, $repo: String!, $pr: Int!) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: $pr) {
          reviewThreads(first: 100) {
            nodes {
              id
              isResolved
              comments(first: 1) {
                nodes { path line originalLine }
              }
            }
          }
        }
      }
    }
    """
    gql_resp = graphql(threads_query, {"owner": owner, "repo": repo_name, "pr": pr_number})
    threads = (gql_resp.get("data", {})
                       .get("repository", {})
                       .get("pullRequest", {})
                       .get("reviewThreads", {})
                       .get("nodes", []))

    resolve_keys = {(c["path"], c["line"]) for c in resolved_to_collapse}

    resolve_mutation = """
    mutation($threadId: ID!) {
      resolveReviewThread(input: {threadId: $threadId}) {
        thread { isResolved }
      }
    }
    """
    for thread in threads:
        if thread["isResolved"]:
            continue
        node = (thread.get("comments", {}).get("nodes") or [{}])[0]
        key = (node.get("path", ""), node.get("line") or node.get("originalLine", 0))
        if key in resolve_keys:
            graphql(resolve_mutation, {"threadId": thread["id"]})
            print(f"  resolved thread: {key}")

# ── Final issue comment ───────────────────────────────────────────────────────
post_issue_comment(
    f"🎉 **Pipeline complete!**\n\n"
    f"| | |\n|---|---|\n"
    f"| PR | {pr_url} |\n"
    f"| Rounds | {rounds_done} |\n"
    f"| Files changed | {len(final_code)} |\n"
    f"| Resolved (collapsed) | {len(resolved_findings)} |\n"
    f"| Unresolved (open) | {len(unresolved_findings)} |\n"
)
